version: '3'

services:
  web:
    image: my-library
    build: .
    env_file: .env
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my-library
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
