# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('publisher_date', models.DateField()),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('number_pages', models.IntegerField(default=1)),
                ('bookbinding', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
